sudo: false

language: ruby

rvm:
  - 2.5.3

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

before_install:
  - gem update --system
  - gem install bundler

script: ./scripts/cibuild

notifications:
  email:
    on_success: never
