sudo: false

language: ruby

rvm:
  - 2.4.2

script: ./scripts/cibuild

branches:
  only:
    - gh-pages

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
