sudo: false

language: ruby

rvm:
  - 2.4.0

script: ./scripts/cibuild

branches:
  only:
    - gh-pages     # test the gh-pages branch

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
