language: ruby

rvm:
  - 2.5.3

env:
  global:
    # Speeds up installation of html-proofer.
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

# Use Bundler 2.0.
# See https://docs.travis-ci.com/user/languages/ruby/#bundler-20.
before_install:
  - yes | gem update --system --force
  - gem install bundler

script: bundle exec rake build test:run

notifications:
  email:
    on_success: never
